# NumPy

In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [5]:
b = np.array([[9.0 , 8.0, 7.0], [6.0, 5.0, 4.0]])
b

array([[9., 8., 7.],
       [6., 5., 4.]])

In [7]:
# Get dimmension 
b.ndim

2

In [8]:
#Get Shape
b.shape

(2, 3)

In [9]:
#Get data type
a.dtype

dtype('int32')

In [10]:
# GEt total size
a.nbytes

12

In [24]:
c = np.array([[1,2,3,4,5,6,7],
              [8,9,10,11,12,13,14]])
print(c)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [17]:
# Get a specific elements [r,c]
c[0,5]

6

In [22]:
#Get a specific element [r,c]
c[0,:]



array([1, 2, 3, 4, 5, 6, 7])

In [25]:
#Get specific column []
c[:,1]

array([2, 9])

In [29]:
c[0,2] = 4
c[:, 2] = 100
c

array([[  1,   2, 100,   4,   5,   6,   7],
       [  8,   9, 100,  11,  12,  13,  14]])

### 3-d example

In [35]:
d = np.array([[[1,2],
             [3,4]],
             [[5,6],
             [7,8]]])

print(d)        

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [41]:
d[0,1,1]

4

In [44]:
#ALL 0a matrix
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [47]:
np.ones([2,2,4])

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [50]:
np.full((2,2),99)

array([[99, 99],
       [99, 99]])